name: Auto PR

on:
  push:
    branches:
      - develop

jobs:
  create-pr:
    name: Create PR develop → main
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: repo-sync/pull-request@v2
        name: pull-request-main
        with:
          destination_branch: "main"
          pr_title: "Pulling ${{ github.ref }} into main"
          pr_body: "💥 *An automated PR*"
          pr_draft: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
